// <auto-generated />
namespace RestApi.Migrations.UsersMigrationsSample
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingusert : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingusert));
        
        string IMigrationMetadata.Id
        {
            get { return "201512081014585_adding usert"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
